### ISSUE TITLE
Release as plugin?

### ISSUE THREAD

**Issue by psntr** [tristantbg/kirby3-vimeosync#1]
Hi Tristan,

I was searching on Google a way to fetch Vimeo video directly into the Kirby panel. I was wondering if you are using this as test or it's working on a live website(s)? 

Look forward to hear from you!

**Comment by tristantbg** [comment]
Hi @psntr,

Actually I use it on many websites and it works quite well ! I never took the time to make a proper documentation but should do it anytime soon.

Let me know if you have questions in the meantime.

Best

**Comment by psntr** [comment]
Thank you for your quick reply!

Have you ever using it with the [kirby *new* editor](https://github.com/getkirby/editor) (block component)? 

Best regards!

**Comment by tristantbg** [comment]
No. I use it with regular fields and Kirby Builder, but you can make your own editor block with this sync.

**Comment by psntr** [comment]
Great news, thank you, I will give it a try! I didn't know about Kirby Builder, it looks very similar to the Kirby editor. Out of curiosity, is there a reason you chose Kirby Builder over the Kirby Editor?

**Comment by tristantbg** [comment]
**Editor** is more an enhanced text field and **Builder** a modular blocks system.
