### ISSUE TITLE
Install step and blueprints

### ISSUE THREAD

**Issue by psntr** [tristantbg/kirby3-vimeosync#2]
Hi!

Sorry to promptly add again a message here, but I'm wondering if you could details a bit how you proceed to use the plugin within Kirby? 

What I have managed to do so far:
- Modifying the dot env file to match my token and keys
- Install `Janitor` (from what I saw in your plugin folder `Janitor` is required)
- Have the panel show the various fields (Sync buttons / Get thumbnails)
- Added the following code in **config.php** 
 ```
'bnomei.janitor.jobs' => [
        'vimeosync_getvideos'     => function (Kirby\Cms\Page $page = null, string $data = null) {

            \Bnomei\Janitor::log('vimeosync_getvideos.mask ' . time());

            $job = \VimeoSync\App::getVideos();

            \Bnomei\Janitor::log('vimeosync_getvideos.exit ' . time());
            return [
                'status' => $job ? 200 : 404,
                'label'  => 'Synced!',
            ];
        },
        'vimeosync_getthumbnails' => function (Kirby\Cms\Page $page = null, string $data = null) {

            \Bnomei\Janitor::log('vimeosync_getthumbnails.mask ' . time());

            $job = \VimeoSync\App::getThumbnails();

            \Bnomei\Janitor::log('vimeosync_getthumbnails.exit ' . time());
            return [
                'status' => $job ? 200 : 404,
                'label'  => 'Synced!',
            ];
        },
    ],
```

Not exactly sure what I should put here:
<img width="1477" alt="kirby-vimeo" src="https://user-images.githubusercontent.com/20617539/104321136-90b79280-5526-11eb-924e-0149f6938c71.png">

Do I have to create a "job" in `Janitor`?

Look forward to finally use that in Kirby 🥇 

**EDIT:** I'm testing it on my localhost with a MAMP configuration

**Comment by tristantbg** [comment]
Hi @psntr,

I guess you find out how to setup everything !
Hit Sync video then Get thumbnails and it should work.
If not, you might have an error in your JS console, try to send it to me here.

Best

**Comment by psntr** [comment]
Dear @tristantbg,

Thank you, glad it to make it there! Ok so I clicked the "Sync Video" and the console returns this:

`"Non-static method Bnomei\Janitor::log() should not be called statically"`

it quite long so:
<img width="1232" alt="Screenshot 2021-01-13 at 13 02 48" src="https://user-images.githubusercontent.com/20617539/104405420-3bb86280-55a0-11eb-83f9-e51af541073e.png">

Greetings

**Comment by psntr** [comment]
I tried to remove comment out the `Bnomei\Janitor::log()`, no more error in the console but you must have put it there for a reason.

Now I can see all the videos in the panel. It actually took a bit of time to Sync everything, because I just discovered that the client has over 1000 videos in its library… Which will likely grow months after months.

**Comment by psntr** [comment]
In between, instead of simply commenting it out, I try to parse it like that, and no more console error.
```
'vimeosync_getvideos' => function (Kirby\Cms\Page $page = null, string $data = null) {
            $janitor = new Bnomei\Janitor;
            $janitor->log('vimeosync_getvideos.mask ' . time());
            $job = \VimeoSync\App::getVideos();
            $janitor->log('vimeosync_getvideos.exit ' . time());
            return [
                'status' => $job ? 200 : 404,
                'label'  => 'Synced!',
            ];
        },
        'vimeosync_getthumbnails' => function (Kirby\Cms\Page $page = null, string $data = null) {
            $janitor = new Bnomei\Janitor;
            $janitor->log('vimeosync_getthumbnails.mask ' . time());
            $job = \VimeoSync\App::getThumbnails();
            $janitor->log('vimeosync_getthumbnails.exit ' . time());
            return [
                'status' => $job ? 200 : 404,
                'label'  => 'Synced!',
            ];
        },
```

What do you think?

**Comment by tristantbg** [comment]
Hey @psntr,

The log line is useless indeed... I updated the config example file with a new one.
As for the thousand videos, you can use the FOLDER_ID variable to sync only a specific folder on the Vimeo.

Best

**Comment by psntr** [comment]
Hi @tristantbg,

Ok I'll delete those lines then.  Thanks for the update!

Regarding the FOLDER_ID or even the SYNC button, basically everytime the client upload a new video on VIMEO, the SYNC button will SYNC everything (from either a specific folder or the whole library)?

Cheers

**Comment by tristantbg** [comment]
The sync will be triggered only when you hit the janitor button (unfortunately Vimeo doesn't have webhooks to let an app know when a new video is updated/created).
If you mention the FOLDER_ID, only the videos inside a specific folder on Vimeo will be synced.

**Comment by psntr** [comment]
Thanks, that makes totally sense. I'm trying now to fetch all folders then within each folders having the "sync" button. 

Hopefully it will make the page a bit lighter. Will keep you updated! Thank you for the help so far, highly appreciated!

**Comment by tristantbg** [comment]
> Thanks, that makes totally sense. I'm trying now to fetch all folders then within each folders having the "sync" button.
> 
> Hopefully it will make the page a bit lighter. Will keep you updated! Thank you for the help so far, highly appreciated!

You're welcome.
Nice idea, you can make your own plugin for that. Let me know if you have suggestions to improve this one !

Best
