### ISSUE TITLE
Vimeo subtitles files

### ISSUE THREAD

**Issue by psntr** [tristantbg/kirby3-vimeosync#3]
Hey!

So far it's been a blast using your plugin.  I managed to use showcase instead of folders and play around. But I'm wondering, have you ever been able to get the subtitles from the videos? From the docs, they refer it as `texttracks`, but I'm not able to get it. 

I try to simply append the `texttracks` as a field argument:
`$response  = self::$lib->request(null, ['fields' => 'uri,modified_time,created_time,name,description,link,pictures,files,texttracks', 'per_page' => 1], 'GET');`

Any hint would be appreciated!

**Comment by tristantbg** [comment]
Hi,

Glad the plugin is useful !

For the texttracks I think you need to make a new query to get them :

"texttracks": {
    "options": [ "string" ],
    "total": 2,
    "uri": "/videos/258684937/texttracks"
  },

So this query :
"/videos/258684937/texttracks"

With your video ID instead of 258684937

**Comment by psntr** [comment]
Thank you for the answer! I was indeed looking at the wrong place, with the correct query it works! Thank very much!
