### ISSUE TITLE
Issue since Kirby v.3.6.0

### ISSUE THREAD

**Issue by psntr** [tristantbg/kirby3-vimeosync#4]
Hi!

Just wanted to let you know that the plugin has an error message since the latest release of kirby v.3.6.0. 

This is the error message: `Cannot read properties of undefined (reading 'url')`
Inside the console:
```
TypeError: Cannot read properties of undefined (reading 'url')
    at a.imageOptions (index.js?1632847972:106)
    at fn (index.js?1632847972:106)
    at r (vendor.js:6)
    at a.we [as _t] (vendor.js:6)
    at index.js?1632847972:106
    at a.be [as _l] (vendor.js:6)
    at index.js?1632847972:106
    at a.be [as _l] (vendor.js:6)
    at index.js?1632847972:106
    at a.be [as _l] (vendor.js:6)
error @ index.js:1
```
Do you also have that with your projects?

**Comment by tristantbg** [comment]
Hi @psntr,

This plugin doesn't use any JS so I won't see why it would not work and show this kind of error.
I tried Kirby 3.6 and it works on my end !

**Comment by dev-ofty** [comment]
@tristantbg as always thank you for the quick reply. That's strange indeed, maybe it's due to my modification of your plugin although I also do not use any JS on it. I will try to disable other plugins and see what's going on.

**Comment by psntr** [comment]
@tristantbg thanks for the fast reply! I see that must be an issue on my side.
